# download two different datasets containing images
---
creates: data/abstract.zip
command: 
  - mkdir -p $(dirname {{creates}})
  - curl http://web.student.tuwien.ac.at/~e0326272/testImages_abstract.zip -o {{creates}}
---
creates: data/artphoto.zip
command: 
  - mkdir -p $(dirname {{creates}})
  - curl http://web.student.tuwien.ac.at/~e0326272/testImages_artphoto.zip -o {{creates}}

# unzip the images into a common directory
---
creates: data/img
depends:
  - data/abstract.zip
  - data/artphoto.zip
command: 
  - rm -rf {{creates}}
  - mkdir -p {{creates}}
  - for archive in {{depends|join(' ')}}; do unzip -d {{creates}} $archive; done

# this is an example of how to use regular expressions to make it easy
# to run an analysis on one file at a time rather than doing every
# image file. the data/img dependency sets up the dependency on the
# previous task. the regular expression makes it possible to run this
# one file at a time.
---
alias: data/rgb
creates: "data/rgb/{{subdirectory}}/{{rootname}}.dat"
depends:
  - src/calculate_pixel_rgb.py
  - data/img/(?P<subdirectory>\w+)/(?P<rootname>\w+).jpg
  - data/img
command:
  - mkdir -p $(dirname {{creates}})
  - python {{depends|join(' ')}} > {{creates}}